### ISSUE TITLE
ModuleNotFoundError: No module named 'customStylesListPA'

### ISSUE THREAD

**Issue by BlipOnNobodysRadar** [DenOfEquity/PixArt-Sigma-for-webUI#2]
```
Launching Web UI with arguments: --xformers --api
*** Error loading script: pixart_diffusers.py
    Traceback (most recent call last):
      File "/home/blip/Desktop/AI/stable-diffusion-webui/modules/scripts.py", line 515, in load_scripts
        script_module = script_loading.load_module(scriptfile.path)
      File "/home/blip/Desktop/AI/stable-diffusion-webui/modules/script_loading.py", line 13, in load_module
        module_spec.loader.exec_module(module)
      File "<frozen importlib._bootstrap_external>", line 883, in exec_module
      File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
      File "/home/blip/Desktop/AI/stable-diffusion-webui/extensions/PixArt-Sigma-for-webUI/scripts/pixart_diffusers.py", line 21, in <module>
        import customStylesListPA as styles
    ModuleNotFoundError: No module named 'customStylesListPA'

---
```

Would love to get this working. I tried adding

```
diffusers>=0.28.1
tokenizers>=0.19
transformers==4.40
```

to requirements.txt but it doesn't seem to have made a difference. I am using auto1111 webui rather than forge.

---
There is customStylesList.py and modelsListPA.py but no customStylesListPA.py maybe just a minor typo?

Solution:

I edited line 21 of pixartdiffusers.py 

from `import customStylesListPA` as styles to `import customStylesList` as styles and it progressed. Seems I was missing peft in addition to the recommended requirements. I installed them inside the venv and now it launches just fine.

**Comment by BlipOnNobodysRadar** [comment]
There is customStylesList.py and modelsListPA.py but no customStylesListPA.py

**Comment by DenOfEquity** [comment]
Thanks for reports.
Styles list was effectively a typo. The 'real' error is that I forgot to rename the file on github.
Initially the file was called **customStylesList.py**, but I changed it when I realised that all my extensions for various models would use the same file rather than the one in their directory, so I gave them unique names as a quick fix. The styles file *should* be called **customStylesListPA.py** so that it can be unique to PixArt.
And Peft is needed for flash; I'll update the requirements in the README as it seems it's not in the base install.
